repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.3
    hooks:
    - id: python-safety-dependencies-check
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.1
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
        - id: isort
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
- repo: https://github.com/myint/docformatter
  rev: v1.3.1
  hooks:
    - id: docformatter
      args: [--in-place]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-aws-credentials
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: pretty-format-json
    -   id: sort-simple-yaml
    -   id: trailing-whitespace
